language: php
# Tests will be for each version in `php` combined with each node version in `env`
php:
  - 5.5
env:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
git:
  depth: 3
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - git clone git@github.com:phase2/pattern-lab-starter.git ../pattern-lab-starter
install:
  - echo "TRAVIS_BUILD_DIR - $TRAVIS_BUILD_DIR" && echo 'pwd - ' && pwd
  - cd ../pattern-lab-starter && npm link ../p2-theme-core
before_script:
  - php --version
  - node --version
  - npm --version
script:
  - npm test
  - cd ../pattern-lab-starter && npm run compile
notifications:
  flowdock:
    secure: RBLFcGBNV8iBA3pBGqGzq5o2Kt+X0IESDtuWnamGurhXItdd0Qh8LZwGmbcZdBuncJQ/WvC5/umCZykf0BeMOiu5TnhJKH3ett0qQT8dxJI9aykwbk/+xyCX09tQJ6jejhcDmu394SUlXYb8DBPnlmE345EVbtjFt9Wxo+ZskCo=
