css:
  enabled: true
  src:
    - src/scss/**/*.scss
  dest: dest/
  lint: true
  # enables additional debugging information in the output file as CSS comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: 'expanded'
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 9
  includePaths:
    - ./node_modules
js:
  enabled: true
  src:
    - src/js/**/*.js
  dest: dest/
  destName: all.min.js
  sourceMapEmbed: true
  babel: true
  eslint:
    enabled: true
    src:
      - src/js/**/*.js
      - gulpfile.js
patternLab:
  enabled: true
  src:
    data: src/data/
    patternLabFiles: src/patternlab-files/
    patterns: src/patterns/
    patternLabCss: src/patternlab-css/
  dest: dest/pattern-lab/
#  config: config--pattern-lab.json # WIP - do not enable
  injectFiles:
#    - bower_components/modernizr/modernizr.js
  injectBower: true
icons: # https://github.com/nfroidure/gulp-iconfont
  enabled: true
  src: src/images/icons/src/*.svg
  dest: dest/
  fontPathPrefix: ''
  classNamePrefix: icon
  autohint: false
  normalize: true
  templates:
    enabled: true
    css:
      src: src/images/icons/templates/_icons.scss
      dest: src/scss/00-config/
    demo:
      src: src/images/icons/templates/icons.mustache
      dest: src/patterns/00-atoms/04-images/
  formats:
    - ttf
    - eot
    - woff
    - svg
browserSync:
  enabled: true
  port: 3050
  watchFiles:
    # - template.php
  # domain: mysite.dev # enable when full CMS is set up
  baseDir: ./
  startPath: dest/pattern-lab/
  openBrowserAtStart: false
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
  tunnel: true
  reloadDelay: 50
  reloadDebounce: 750
drupal:
  enabled: false
  # when these files change
  watch:
    - template.php
    - templates/**
  # run this command
  command: drush cc all
  # in this directory
  dir: ./
  inject:
    bower: true
    file: theme.info
